const USERS = {
  LOADING: 'USERS_LOADING',
  FETCH_SUCCESS: 'USERS_FETCH_SUCCESS',
  FETCH_ERROR: 'USERS_FETCH_ERROR',
};

const POSTS = {
  FETCH_SUCCESS: 'POSTS_FETCH_SUCCESS',
  FETCH_ERROR: 'POSTS_FETCH_ERROR',
  SUBMIT_SUCCESS: 'POSTS_SUBMIT_SUCCESS',
  SUBMIT_ERROR: 'POSTS_SUBMIT_ERROR',
  DELETE_SUCCESS: 'POSTS_DELETE_SUCCESS',
  DELETE_ERROR: 'POSTS_DELETE_ERROR',
  EDIT_SUCCESS: 'POSTS_EDIT_SUCCESS',
  EDIT_ERROR: 'POSTS_EDIT_ERROR',
  FETCH_COMMENTS_SUCCESS: 'FETCH_COMMENTS_SUCCESS',
  FETCH_COMMENTS_ERROR: 'FETCH_COMMENTS_ERROR',
  SUBMIT_COMMENT_SUCCESS: 'SUBMIT_COMMENT_SUCCESS',
  SUBMIT_COMMENT_ERROR: 'SUBMIT_COMMENT_ERROR',
  DELETE_COMMENTS_SUCCESS: 'DELETE_COMMENTS_SUCCESS',
  DELETE_COMMENTS_ERROR: 'DELETE_COMMENTS_ERROR',
  EDIT_COMMENTS_SUCCESS: 'EDIT_COMMENTS_SUCCESS',
  EDIT_COMMENTS_ERROR: 'EDIT_COMMENTS_ERROR',
};

const MEDIA = {
  ALBUMS_FETCH_SUCCESS: 'ALBUMS_FETCH_SUCCESS',
  ALBUMS_FETCH_ERROR: 'ALBUMS_FETCH_ERROR',
  PHOTOS_FETCH_SUCCESS: 'PHOTOS_FETCH_SUCCESS',
  PHOTOS_FETCH_ERROR: 'PHOTOS_FETCH_ERROR',
};

export {
  USERS,
  POSTS,
  MEDIA,
};